name: Selenium Test Execution

on:
  push:
    branches: [ "main", "test", "yogi" ]
  pull_request:
    branches: [ "main", "test", "yogi" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run Tests with Virtual Display
        run: xvfb-run --server-args="-screen 0 1280x1024x24" mvn test

      - name: Debug test outputs
        run: ls -R

      - name: Upload Execution Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: execution-reports
          path: |
            recordings/
            screenshots/
            test-output/
          if-no-files-found: warn
